MODEL:
  DEVICE: "cuda"
  DEVICE_ID: ('0')
  MODE: 'train'
  DETECTION: 'gt' # {'gt' | 'MVDeTr'}
  RESUME: false
  LAST_CKPT_FILE: './'

DATASET:
  DIR: './datasets/'
  NAME: 'SelfDataset'
  SEQUENCE: ['sequence1']
  CAMS: 3
  TOTAL_FRAMES: 149

FE: # Feature Extractor
  CHOICE: 'CNN'
  INPUT_SIZE: (256, 128)

SOLVER:
  TYPE: 'SG' # {'SG': Spatial Graph, 'TG': Temporal Graph}
  EPOCHS: 100
  EVAL_EPOCH: 2
  BATCH_SIZE: 32
  LR: 0.01 # Learning Rate
  MAX_PASSING_STEPS: 4
  W: 3 # Temporal Window Size
  W_TEST: 5
  FOCAL_ALPHA: 0.98
  FOCAL_GAMMA: 5

OUTPUT:
  VISUALIZE: True
  LOG: True
  CKPT_DIR: './logs/ckpts'
  INFERENCE_DIR: './logs/inference'

TEST:
  CKPT_FILE_SG: './logs/ckpts/Wildtrack_sequence1_SG_epoch92_train90.pth'
  CKPT_FILE_TG: './logs/ckpts/Wildtrack_sequence1_TG_epoch72_train90.pth'
  FRAME_START: 0
  EDGE_THRESH: 0.9